### ISSUE TITLE
TypeError: text.replace is not a function

### ISSUE THREAD

**Issue by olonsoft** [stackhero-io/node-red-contrib-stackhero-influxdb-v2#12]
The following is the payload that I send and the error that I get:

```json
{
  "payload": {
    "bucket": "weather-data",
    "precision": "ms",
    "data": [
      {
        "measurement": "weatherdata",
        "tags": {
          "device_sn": "SK-00000732",
          "firmware_revision": 43,
          "report_interval": 1,
          "wind_sample_interval": 3,
          "precipitation_type": 0
        },
        "fields": {
          "wind_speed": 0.89,
          "wind_lull": 0,
          "wind_gust": 1.74,
          "wind_direction": 144,
          "uv_index": 0,
          "illuminance": 0,
          "solar_radiation": 0,
          "battery": 3.25,
          "rain_accumulated": 0
        },
        "timestamp": 1615224793257
      }
    ]
  },
  "_session": {
    "type": "websocket",
    "id": "315a89d2.d2f9f6"
  },
  "_msgid": "ea8958bf.3574c8",
  "error": {
    "message": "TypeError: text.replace is not a function",
    "source": {
      "id": "ceb1cd06.6c177",
      "type": "Stackhero-InfluxDB-v2-write",
      "name": "influxdb2write",
      "count": 1
    },
    "stack": "TypeError: text.replace is not a function\n    at escape (/data/node_modules/influxdb-v2/src/index.js:101:25)\n    at Object.keys.map.tagKey (/data/node_modules/influxdb-v2/src/index.js:107:67)\n    at Array.map (<anonymous>)\n    at lines.map (/data/node_modules/influxdb-v2/src/index.js:107:12)\n    at Array.map (<anonymous>)\n    at Influxdb.write (/data/node_modules/influxdb-v2/src/index.js:95:8)\n    at InfluxDbV2Node.write (/data/node_modules/node-red-contrib-stackhero-influxdb-v2/src/main.js:28:34)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
  }
}
```

**Comment by tito** [comment]
I got this error too. It appears that passing non-string in tags is what throw an exception.
By using `JSON.stringify()` on all tags, it worked.
