### ISSUE TITLE
Uncaught Exception:TypeError: Cannot create property 'data' on number ...

### ISSUE THREAD

**Issue by ZmRZjFuDsDiR4qi5801F** [stackhero-io/node-red-contrib-stackhero-influxdb-v2#20]
Hello, we tried the node to connect to influxdb version 2 on our Bosch Rexroth ctrlX Hardware (Linux Ubuntu Core arm64). Unfortunately right after deploy, the Node.js process crashes caused by an Uncaught Exception of your node.

It seems to be caused by some internal conversions. Please could you provide us a fix for this or give us a hint if there's a workaround. Thank you in advance 

Please see the callstack for details:

...
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]: 7 Dec 09:17:56 - [red] Uncaught Exception:
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]: 7 Dec 09:17:56 - [error] TypeError: Cannot create property 'data' on number '11.6'
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]:     at InfluxDbV2NodeWrite._inputCallback (/var/snap/rexroth-solutions/common/solutions/DefaultSolution/configurations/appdata/node-RED/node_modules/node-red-contrib-stackhero-influxdb-v2/src/write.js:37:26)
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]:     at [/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26](mailto:/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26)
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]:     at Object.trigger ([/snap/ctrlx-node-red/674/lib/node_modules/@node-red/util/lib/hooks.js:166:13](mailto:/snap/ctrlx-node-red/674/lib/node_modules/@node-red/util/lib/hooks.js:166:13))
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]:     at InfluxDbV2NodeWrite.Node._emitInput ([/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11](mailto:/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11))
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]:     at InfluxDbV2NodeWrite.Node.emit ([/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25](mailto:/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25))
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]:     at InfluxDbV2NodeWrite.Node.receive ([/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10](mailto:/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10))
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]:     at Immediate.<anonymous> ([/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52](mailto:/snap/ctrlx-node-red/674/lib/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52))
2022-12-07T09:17:56Z ctrlx-node-red.node-red[11962]:     at processImmediate (node:internal/timers:466:21)

**Comment by AngeloHulshout** [comment]
Same problem here. Did you resolve this, or are we still waiting on a response from Stackhere?

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
We're still waiting for any response or fix. Can anyone give us some information or schedule about that?
